### ISSUE TITLE
Make the script log the IP address in the log-file

### ISSUE THREAD

**Issue by wienke** [TheThingsNetwork/kerlink-station-firmware#3]
Would that be possible. This way you can find out the IP address without having to scan your DHCP server.

**Comment by FRVisser** [comment]
Yes very easy. But it could change afterwards.

**Comment by FRVisser** [comment]
I cannot find what is writing this log file for now. But if this would be added, it probably works:
``` shell
ifconfig eth0 | grep -E "(inet addr:)" | head -n 1 | awk '{ print $2}' | cut -c 6-
```
