### ISSUE TITLE
More information about dota generation

### ISSUE THREAD

**Issue by sabrine2020** [TheThingsNetwork/kerlink-station-firmware#4]
Hello,

I am getting starting with kerlink and I tested this dota package dota_thethingsnetwork_v1.3_EU.tar.gz to connect it to the TTN. It is working OKey.
I am curious about how this dota package has been generated? could you provide more information about this please?

Thanks.
Best regards

**Comment by egourlao** [comment]
The best way to know more about the DOTA file is to untar it, with `tar -xvzf <dota file>`. It contains files that are also present in this repository or in other TTN repositories:
+ `bin/poly_pkt_fwd`, from this repository.
+ The configuration file comes from [`gateway-conf`](https://github.com/TheThingsNetwork/gateway-conf/blob/master/EU-global_conf.json).

**Comment by FRVisser** [comment]
Generating Dota's files is explained on the Kerlink wiki. In general, it is a tar package with all files in the root of the package and with right ownership set on the files. 

I looked back. The command I used was like:
```
cd ../dota_thethingsnetwork_SmartParcs_v1.5
tar --owner=root --group=root -cvzf ../dota_thethingsnetwork_SmartParcs_v1.5.tar.gz begin_dota.sh end_dota.sh etc knet mnt
```

The packet forwarder is the (now legacy) poly packet forwarder.  Cross-compiled with the Kerlink toolchain and Docker. 

Installation is done with `begin_dota.sh` and configuration with `end_dota.sh`. Respectively, executed before and after automated copying the complete contents of the tar file.

**Comment by sabrine2020** [comment]
I see thanks! 

So if I understood the procedure, you have not exactly followed the procedure in the kerlink wiki to use the semtech packet forwarder (they are providing scripts to build the semtech sources and then generating the dota). 
Instead you have prepared the tar package containing:
* the generated bin from semtech, 
* the needed configuration file, etc...
right?

Is it because using the dota file provided by kerlink is not compatible with the TTN network server? Or it is just because kerlink dota are licence protected.

Thanks & Best regards
